version: '3'
services:
    chatbot_server:
        build: 
            dockerfile: Dockerfile
            context: . 
        ports:
            - "5000:5000"

#     web_server:
#         restart: always
#         build: 
#           dockerfile: dockerfile
#           context: ./web
#         ports: 
#           - '5000:80'

networks:
    chat-bot:
        driver: bridge