version: '3'
services:
    chatbot_server:
        build: 
            dockerfile: dockerfile
            context: .
        container_name: chatbot_server
        ports:
            - "5000:5000"
        volumes:
            - "./datenbank:/usr/src/datenbank"

#     web_server:
#         restart: always
#         build: 
#           dockerfile: dockerfile
#           context: ./web
#         ports: 
#           - '5000:80'