version: '3'
services:
    chatbot_server:
        build: 
            dockerfile: dockerfile
            context: .
        container_name: chatbot_server
        ports:
            - "5000:5000"
        volumes:
            - "./datenbank:/usr/src/datenbank"